export const AuthEvents = {
  REGISTER_SUBADMIN: "AUTH_REGISTER_SUBADMIN",
  LOGIN: "AUTH_LOGIN",
  LOGOUT: "AUTH_LOGOUT",
  REFRESH_TOKEN: "AUTH_REFRESH_TOKEN",

  FORGOT_PASSWORD: "AUTH_FORGOT_PASSWORD",
  VERIFY_OTP: "AUTH_VERIFY_OTP",
  RESET_PASSWORD: "AUTH_RESET_PASSWORD",
  CHANGE_PASSWORD: "AUTH_CHANGE_PASSWORD",

  DEVICE_DETECTED: "AUTH_DEVICE_DETECTED",
  UNUSUAL_ACTIVITY: "AUTH_UNUSUAL_ACTIVITY",
};